# Only use standardrb, but keep .rubocop.yml for tool compatibility: https://github.com/standardrb/standard#running-standards-rules-via-rubocop
require:
  - standard
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
